### PR TITLE
Remove kinpy as a dependency

### PR DESCRIPTION
**Pull request by varunagrawal**
Following from #242.

### CODE REVIEW

**Review by dellaert — CHANGES_REQUESTED** [review]
Why are we doing this? kinpy is a great check on our kinematics, no?

**Comment by varunagrawal** [comment]
Yes but we don't use it anywhere else. Having users import a package (e.g. on a robot) that doesn't provide core functionality seems wasteful.

Plus, I had kinpy print out the FK transforms and added them as regression values so that the test still does the same job. :)

**Review by dellaert — APPROVED** [review]
OK, thanks, that clears it up :-) !

**Comment by dellaert** [comment]
Note, some checks seem to be failing...

**Pull request merged**
