### PR TITLE
Jumping Robot Python Tests

### PR DESCRIPTION
**Pull request by varunagrawal**
Adds tests for the Jumping Robot to the CI.

Currently 2 tests fail. @yetongumich can you please also look into this since I will not get to it until the 11/30.

### CODE REVIEW

**Comment by varunagrawal** [comment]
It isn't. It was some pending changes I wanted to get out of the way before I lost them to the void.

**Comment by dellaert** [comment]
CI fails

**Comment by varunagrawal** [comment]
Yup, my PR comment explicitly asks Yetong to look into this since he's the owner of this codebase.

**Comment by varunagrawal** [comment]
The issue is that the Python tests for the Jumping Robot were never added to the CI until now, that's why you're seeing the tests fail in this PR.

**Comment by yetongumich** [comment]
Sorry I just noticed this PR review. It seems the two libraries `matplotlib` and `yaml` may not be installed in the travis Python version. I'll make a commit into this branch to handle that.

**Review by yetongumich — APPROVED** [review]

**Comment by yetongumich** [comment]
The previous CI fail due to the `pyyaml` package dependency, and the update on the Link constructor. After revising the issues, all checks have passed.

**Pull request merged**
