### PR TITLE
Link class refactored to remove world context. 

### PR DESCRIPTION
**Pull request by dellaert**

### CODE REVIEW

**Comment by dellaert** [comment]
@varunagrawal we merged to a branch not master. Can you approve so we can merge Dan's PR into master? @danbarla and I created Issue #260 to bring back wTl as bMlink.

**Review by varunagrawal — APPROVED** [review]
LGTM but we should keep an eye on resolving #80

**Comment by varunagrawal** [comment]
In general it would be a good idea to link PRs to issues so we can track progress given we have a good amount of activity going on. :slightly_smiling_face:

**Comment by dellaert** [comment]
> LGTM but we should keep an eye on resolving #80

Yeah, this PR goes towards #80

**Pull request merged**
