### PR TITLE
Updated instructions for source install of SDFormat10

### LINKED ISSUE #266: sdfformat on Ubuntu
I can't get sdformat to install on Linux with instructions on website.  I did:

```bash
apt-get -y install libtinyxml2-dev libxml2-utils pkg-config ruby-dev ruby wget
apt-get -y install libignition-math4-dev
cd /usr/src
wget http://osrf-distributions.s3.amazonaws.com/sdformat/releases/sdformat-10.5.0.tar.bz2
tar -xvjf sdformat-10.5.0.tar.bz2
rm -f sdformat-10.5.0.tar.bz2
mkdir build
cd build
cmake ..
```

But get

```
====== Finding 3rd Party Packages ======
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Building for arch: x86_64
-- Found TinyXML2: /usr/lib/x86_64-linux-gnu/libtinyxml2.so  
-- Checking for module 'urdfdom>=1.0'
--   No package 'urdfdom' found
CMake Warning at cmake/SearchForStuff.cmake:34 (find_package):
  By not providing "Findurdfdom.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "urdfdom", but
  CMake did not find one.

  Could not find a package configuration file provided by "urdfdom" with any
  of the following names:

    urdfdomConfig.cmake
    urdfdom-config.cmake

  Add the installation prefix of "urdfdom" to CMAKE_PREFIX_PATH or set
  "urdfdom_DIR" to a directory containing one of the above files.  If
  "urdfdom" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:116 (include)


-- Couldn't find urdfdom >= 1.0, using internal copy
CMake Warning at cmake/SearchForStuff.cmake:55 (find_package):
  By not providing "Findignition-tools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-tools", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-tools"
  with any of the following names:

    ignition-toolsConfig.cmake
    ignition-tools-config.cmake

  Add the installation prefix of "ignition-tools" to CMAKE_PREFIX_PATH or set
  "ignition-tools_DIR" to a directory containing one of the above files.  If
  "ignition-tools" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:116 (include)


-- 	ignition-tools not found, for command line utilities and for generating aggregated SDFormat descriptions for sdformat.org, please install ignition-tools.
-- Could NOT find PY_psutil (missing: PY_PSUTIL) 
-- 	Python psutil package not found. Memory leak tests will be skipped
-- Found ruby executable: /usr/bin/ruby
CMake Error at cmake/SearchForStuff.cmake:107 (find_package):
  By not providing "Findignition-cmake2.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-cmake2", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-cmake2"
  (requested version 2.3) with any of the following names:

    ignition-cmake2Config.cmake
    ignition-cmake2-config.cmake

  Add the installation prefix of "ignition-cmake2" to CMAKE_PREFIX_PATH or
  set "ignition-cmake2_DIR" to a directory containing one of the above files.
  If "ignition-cmake2" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:116 (include)


-- Configuring incomplete, errors occurred!
```

I can update the README, but can someone comnment on how they got past this? I hope it does not involve also installing urfdom from source etc...

### PR DESCRIPTION
**Pull request by varunagrawal**
The title. Should resolve #266.

### CODE REVIEW

**Comment by dellaert** [comment]
On an Ubuntu 18.04 image, I still get a cmake error:

```
====== Finding 3rd Party Packages ======
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Building for arch: x86_64
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TinyXML2 (missing: TINYXML2_LIBRARY TINYXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindTinyXML2.cmake:31 (find_package_handle_standard_args)
  cmake/SearchForStuff.cmake:11 (find_package)
  CMakeLists.txt:116 (include)


-- Configuring incomplete, errors occurred!
See also "/usr/src/gtsam/build/sdformat-10.5.0/build/CMakeFiles/CMakeOutput.log".
```

**Comment by varunagrawal** [comment]
I'm re-running the instructions in a new docker instance to double check.

**Comment by varunagrawal** [comment]
That's weird, I'm getting this:

```
====== Finding 3rd Party Packages ======
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Building for arch: x86_64
-- Found TinyXML2: /usr/lib/x86_64-linux-gnu/libtinyxml2.so  
-- Checking for module 'urdfdom>=1.0'
--   Found urdfdom, version 1.0.0
-- Looking for ignition-tools-config.cmake - found
-- Could NOT find PY_psutil (missing: PY_PSUTIL) 
-- 	Python psutil package not found. Memory leak tests will be skipped
-- Found ruby executable: /usr/bin/ruby
-- Looking for ignition-math6-config.cmake - found
-- ----------------------------------------
```

Are you running an `apt-get -y update` as the first step in the docker image? Can you please post the full log?

**Comment by dellaert** [comment]
I updated the DockerFile in feature/docker. Same error even after I did update

**Comment by varunagrawal** [comment]
You're missing the line to actually install the gazebo packages (aka `SDFormat Dependencies`). I'm pushing a commit to that branch.

**Review by dellaert — APPROVED** [review]

**Comment by dellaert** [comment]
> You're missing the line to actually install the gazebo packages (aka `SDFormat Dependencies`). I'm pushing a commit to that branch.

Thanks!!!!

**Comment by varunagrawal** [comment]
Absolutely, it's what I'm here for. 🙂

**Pull request merged**
