### PR TITLE
Python wrapper update

### PR DESCRIPTION
**Pull request by gchenfc**
I found this cleaning up old local stashes - I think it was needed by Natalie at one point but then wasn't anymore; in any case, it's probably useful to have wrapped still.

@nrakoski3 , if you have time could you make a short unit test for IK drawing from some of your code, as well as tests for any other classes you need from gtdynamics?  I might recommend putting it in `test_forward_kinematics.py` then renaming the file to just `test_kinematics.py`

### CODE REVIEW

**Comment by varunagrawal** [comment]
The `PointGoalFactor` might be removed soon. Otherwise this PR looks great.
Can you add some simple unit tests please?

**Review by dellaert — APPROVED** [review]

**Comment by dellaert** [comment]
Jerry please add quick unit test before merging. Also merge in master so CI checks that

**Comment by gchenfc** [comment]
will do (after fixing cablerobot segfault)

**Comment by varunagrawal** [comment]
Ping @gchenfc

**Comment by varunagrawal** [comment]
I added the unit tests, merging.

**Pull request merged**
